### ISSUE TITLE
Select a base class for spectrum

### ISSUE THREAD

**Issue by hamogu** [hamogu/astrospec#3]
Reasonable choices might be:
- astropy.nddata.NDData
- astropy.units.Quantity
- nothing (and have data and wavelength as members)
  - data could be a quantity 
  - or an ndarray

Some loose thoughts:
- NDData seems like a good fit, but is under active development. We are likely to see changes in the NDData API and will have to adapt to it as time goes on.
- NDData was actually designed with 2 use cases in mind: Spectrum and CCD imaging.
- Quantitiy is a lot more mature than NDData. It brings in a lot of numpy array methods (min, max, mean, sum, ...). On the one hand that convolutes the namespace a little, on the other hand we might want much of that.
- Related: Some reasonable use cases (`spectrum / 4 / np.pi / (15. * unit.parsec)**2`) will not (yet?) work out of the box for NDData, but would for a quantity.
- Numerical operations with quantities are sometimes significantly slower than plain numpy. NDData is untested in that regard, but probably even slower (see e.g. https://github.com/astropy/astropy/issues/3908#issuecomment-176782129).
- In NDData, `unit`, `data`, etc. are properties without a setter. That was a deliberate design decision - users should be prevented from changing these things in place, because mask, unit, uncertainty and data would get out of sync. (E.g. if If do `spectrum.data[5:25] = np.arange(20)`, then `spectrum.uncertainty` certainly also needs to be changed). Thus, we would need setter methods for all this stuff or use the approach "a spectrum object should be treated as immutable and all operations return a new spectrum object".
  I understand why the NDData design was made that why, but I worry about performance implications. (https://github.com/astropy/astropy-APEs/blob/master/APE7.rst)

**Comment by glentner** [comment]
Let's take NDData and go with it. We can close this issue later if we decide to stay with NDData, or we can close it now if you like.
